spring:
  application:
    name: service.service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: "*"

